apiVersion: apps/v1
kind: Deployment
metadata:
    name: users-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: users
    template:
        metadata:
            labels:
                app: users
        spec:
            containers:
                - name: users
                  image: axelmastroianni/users
                  env:
                      # - name: DATABASE
                      #   value: 'mongodb+srv://axel:<PASSWORD>@cluster0.s6xgy.mongodb.net/roba-da-arbitri/users?retryWrites=true&w=majority'
                      # - name: DB_PASSWORD
                      #   value: 0bq5pDpHwD2NHCpp
                      - name: USERS_MONGO_URI
                        value: "mongodb://users-mongo-srv:27017/users"
---
apiVersion: v1
kind: Service
metadata:
    name: users-srv
spec:
    type: NodePort
    selector:
        app: users
    ports:
        - name: users
          protocol: TCP
          port: 5000
          targetPort: 5000
